SPLIT_DATA:
  DATA_PATHS: "/data/Projects/quality-prediction/drive/實驗設計數據/化新 (Beta site)/實驗數據/20231110 (台中精機場域)/OP1 (KB2-1139)/*"
  GCODE_PATH: "/home/huangkaichun/QualityPrediction/化新OP1_Gcode.csv"  # 該訊號的加工 Gcode
  SR: 11024   #震動訊號 sample rate
  SAVE_PATH: "/data/Projects/quality-prediction/dataset/ATRANS/測試/"  #存圖的資料夾，最後要有斜線

MODEL:
  NAME: "sequential_angry_fox"
  PRETRAINED_PATH: "dataset/ATRANS/OR110_8/checkpoint.h5" #model存放位置
  FILTERS: 24
  NUM_LAYERS: 2
  LORA: True
  DROPOUT_RATE: 0.5
  SEQUENCE_LENGTH: 8192

DATASETS:
  # TRAIN_DATA: "dataset/DOE_6/train_datasetSignal.csv" 
  DATA: "dataset/ATRANS/OR110_8/化新場域/datasetSignal0619.csv" #
  FILE_PATHS: "dataset/ATRANS/OR110_8/化新場域/OP1_110_8/0619/*.pickle"
  MACHININGERROR_PATH: "CNC_signal_process/doe4/machining_error.csv" #

DATALOADER:
  NUM_WORKERS: 96
  MAX_QUEUE_SIZE: 4
  WORKPIECE_LENGTH: 20.0
  NORM_MEAN: "dataset/DOE_4th/norm_mean_1to2.npy" #
  NORM_STD: "dataset/DOE_4th/norm_std_1to2.npy"   #

SOLVER:
  BASE_LR: 5e-3
  BATCH_SIZE: 32
  MAX_EPOCHS: 64
  WEIGHT_DECAY: 1e-10

TEST:
  WEIGHT: ""
  EVALUATE_ONLY: "off"
  EVALUATE_DATA: "" 
  LIM_MIN: 0.02
  LIM_MAX: 0.09
  LOCATION: [1]

OUTPUT_DIR: "dataset/ATRANS/OR110_8/化新場域/finetune"
DESCRIPTION: ""

